# Generated by Django 4.2.3 on 2024-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCapsuleComfortImages',
            fields=[
                ('CapsuleID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('modelNumber', models.CharField(max_length=100, null=True)),
                ('brandName', models.CharField(max_length=100, null=True)),
                ('featureType', models.CharField(default='comfort', max_length=100)),
                ('airConditioningImage', models.ImageField(null=True, upload_to='capsule_images/comfort/AC/')),
                ('heatingImage', models.ImageField(null=True, upload_to='capsule_images/comfort/heating')),
                ('freshAirSystemImage', models.ImageField(null=True, upload_to='capsule_images/comfort/freshAirSystem')),
                ('floorHeatingImage', models.ImageField(null=True, upload_to='capsule_images/comfort/floorHeatingImage')),
                ('waterFiltrationSystemImage', models.ImageField(null=True, upload_to='capsule_images/comfort/waterFiltrationSystemImage')),
                ('privacyBlindsImage', models.ImageField(null=True, upload_to='capsule_images/comfort/privacyBlindsImage')),
                ('skylightImage', models.ImageField(null=True, upload_to='capsule_images/comfort/skylightImage')),
                ('blockoutBlindsImage', models.ImageField(null=True, upload_to='capsule_images/comfort/blockoutBlindsImage')),
                ('skylightBlindImage', models.ImageField(null=True, upload_to='capsule_images/comfort/skylightBlindImage')),
                ('otherComfortImage', models.ImageField(null=True, upload_to='capsule_images/comfort/otherComfortImage')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceCapsuleImages',
            fields=[
                ('CapsuleID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('modelNumber', models.CharField(max_length=100, null=True)),
                ('brandName', models.CharField(max_length=100, null=True)),
                ('featureType', models.CharField(max_length=100, null=True)),
                ('mainImage', models.ImageField(upload_to='capsule_images/main/')),
            ],
        ),
    ]
