# Generated by Django 4.2.3 on 2024-08-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCapsuleImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCapsuleEntertainmentImages',
            fields=[
                ('CapsuleID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('modelNumber', models.CharField(max_length=100, null=True)),
                ('brandName', models.CharField(max_length=100, null=True)),
                ('featureType', models.CharField(default='comfort', max_length=100)),
                ('projectImage', models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/projectImage /')),
                ('projectorScreenImage', models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/projectorScreenImage  /')),
                ('intelligentControlPanelImage', models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/intelligentControlPanelImage  /')),
                ('integratedSoundSystemImage', models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/integratedSoundSystemImage /')),
                ('otherEntertainmentImage', models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/otherEntertainmentImage  /')),
            ],
        ),
    ]
