# Generated by Django 4.2.3 on 2024-08-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCapsuleImages', '0002_spacecapsuleentertainmentimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecapsuleentertainmentimages',
            name='featureType',
            field=models.CharField(default='entertainment', max_length=100),
        ),
        migrations.AlterField(
            model_name='spacecapsuleentertainmentimages',
            name='integratedSoundSystemImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/integratedSoundSystemImage/'),
        ),
        migrations.AlterField(
            model_name='spacecapsuleentertainmentimages',
            name='intelligentControlPanelImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/intelligentControlPanelImage/'),
        ),
        migrations.AlterField(
            model_name='spacecapsuleentertainmentimages',
            name='otherEntertainmentImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/otherEntertainmentImage/'),
        ),
        migrations.AlterField(
            model_name='spacecapsuleentertainmentimages',
            name='projectImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/projectImage/'),
        ),
        migrations.AlterField(
            model_name='spacecapsuleentertainmentimages',
            name='projectorScreenImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/projectorScreenImage/'),
        ),
    ]
