# Generated by Django 4.2.3 on 2024-08-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCapsuleImages', '0003_alter_spacecapsuleentertainmentimages_featuretype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacecapsuleentertainmentimages',
            name='integratedSoundSystemImage',
        ),
        migrations.RemoveField(
            model_name='spacecapsuleentertainmentimages',
            name='intelligentControlPanelImage',
        ),
        migrations.RemoveField(
            model_name='spacecapsuleentertainmentimages',
            name='otherEntertainmentImage',
        ),
    ]
