# Generated by Django 4.2.3 on 2024-08-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCapsuleImages', '0004_remove_spacecapsuleentertainmentimages_integratedsoundsystemimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacecapsuleentertainmentimages',
            name='integratedSoundSystemImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/integratedSoundSystemImage/'),
        ),
        migrations.AddField(
            model_name='spacecapsuleentertainmentimages',
            name='intelligentControlPanelImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/intelligentControlPanelImage/'),
        ),
        migrations.AddField(
            model_name='spacecapsuleentertainmentimages',
            name='otherEntertainmentImage',
            field=models.ImageField(blank=True, null=True, upload_to='capsule_images/entertainment/otherEntertainmentImage/'),
        ),
    ]
